language: python
sudo: false

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
    - "pypy3"

os:
    - osx
    - linux

install:
    - pip install --upgrade pip
    - pip install .
    - pip install DragonPyEmulator
#    - pip install -e git+https://github.com/jedie/DragonPy.git#egg=dragonpy -v
    - pip install coveralls

script:
    - python -c "import sys;print('\n'.join(sys.path))"
    - coverage run --source=MC6809 ./setup.py nosetests
#    - coverage run --source=MC6809 DragonPy nosetests
    - export DRAGONPY_PATH=$(python -c "import os,dragonpy;print(os.path.abspath(os.path.dirname(dragonpy.__file__)))")
    - echo ${DRAGONPY_PATH}
    - cd
    - coverage run --source=MC6809 -m "nose" --where=${DRAGONPY_PATH}

after_success:
    - coveralls

notifications:
    irc: "irc.freenode.org#pylucid"
