language: python
python:
  - "2.7"
  - "pypy"
install: true
# There is no dependencies, yet.
#  - pip install coveralls
#script:
#  coverage run --source=dragonpy setup.py test
#after_success:
#  coveralls