language: python
sudo: false

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
    - "pypy3"

os:
    - osx
    - linux

install:
    - pip install --upgrade pip
    - pip install -e git+https://github.com/jedie/DragonPy.git#egg=dragonpy
    - pip install .
    - pip install coveralls

script:
    - coverage run --source=MC6809 ./setup.py nosetests
    - coverage run --source=MC6809 DragonPy nosetests

after_success:
    - coveralls

notifications:
    irc: "irc.freenode.org#pylucid"
