language: python
python:
  - "2.7"
  - "pypy"
install: true # There is no dependencies, yet.
#  - pip install coveralls
script:
  - python setup.py test
#  coverage run --source=dragonpy setup.py test
#after_success:
#  coveralls
branches:
  only:
    - master
    - stable