# Config file for automatic testing at travis-ci.org

language: python

python:
    - "2.7"
    - "3.4"
    - "pypy"

install:
    - "pip install ."
    - "pip install dragonlib coveralls"

script:
    # - python -m unittest discover
    - coverage run ./setup.py test

after_success:
    coveralls

branches:
    only:
        - master
        - stable

notifications:
    irc: "irc.freenode.org#pylucid"
