language: python
sudo: false

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
    - "pypy3"

os:
    - osx
    - linux

install:
    - pip install --upgrade pip
    - pip install .
    - pip install coveralls

script:
    - coverage run --source=MC6809 ./setup.py nosetests

after_success:
    - coveralls

# OSX builds do not yet support Python :(
# see: https://github.com/travis-ci/travis-ci/issues/2312
matrix:
  allow_failures:
    - os: osx

notifications:
    irc: "irc.freenode.org#pylucid"
