language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
install: true # There is no dependencies, yet.
#  - pip install coveralls
script:
  # "python setup.py test" will not run the tests from dragonlib
  - python -m unittest discover
#  coverage run --source=dragonpy setup.py test
#after_success:
#  coveralls
branches:
  only:
    - master
    - stable